spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  h2:
    console:
      #enabled: false
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop
    show-sql: true

security:
  enable: true
  #enable: false